[#8] 과거 채팅방 노출 및 채팅방 제목 짓기
f-lab-edu/mezero-chat pull request #9
Opened 2024-10-09 07:58 UTC by nayoungace

**현재 상황**
- 과거 채팅방을 열람할 수 없다.

**구현 목표**
- 과거 질문 및 답변 리스트를 좌측에 노출하고, 클릭 시 해당 채팅방으로 이동한다.
- 채팅방 제목을 지어준다.
- 기준 : 처음 GPT로부터 답변이 왔을 때, 이후 대화가 10회 진행될 때마다 다시 제목 짓기

2024-10-10 03:16 UTC, f-lab-crack requested changes
코멘트 한번 확인해주시고, 수정해주세요.

2024-10-10 03:16 UTC, f-lab-crack commented on app/chat/ChatDetailPage.tsx
> +  const initChat = async () => {
요기서 'id'를 initChat의 parameter로 넘겨주면 더 좋을듯

2024-10-10 03:16 UTC, f-lab-crack commented on app/chat/ChatDetailPage.tsx
> +  }, []);
dependency에 [id]가 되어야 할거 같아요. initChat의 parameter로 id를 안넘겨서 이런 실수가 나온듯

2024-10-10 03:16 UTC, f-lab-crack commented on business/ChatService.ts
> +    return answerChat.title;
이 함수는 이름하고 함수가 하는 일하고 조금 달라요.

이름만 봐서는 'chat 타이틀 만드는건가보다' 하는데
실제로는 타이틀 만들고 나서 chat 자체를 업데이트까지 하고 있어요.

저같으면 'updateChatTitle' 정도로 할거 같아요. 

그리고, 이 함수는 잠재적인 버그가 있어요.

 'this.getAnswer'를 실행하는데 시간이 조금 걸릴 수 있는데요.. 왜냐면 내부에서 OpenAi의 api를 호출하고 답을 기다릴테니까요.
이 사이에 사용자가 새로운 chatlog를 생성하면, 그 chatlog를 날라가 버릴거에요.

이런 문제를 'race condition'이라고 하는데, 이런 문제를 해결하려면 어떻게 하면 좋을지 한번 고민해봐주세요.

2024-10-10 03:16 UTC, f-lab-crack commented on business/ChatService.ts
> +  }
이 함수도 race condition 문제가 있습니다.

2024-10-12 03:46 UTC, nayoungace commented on app/chat/ChatDetailPage.tsx
> +  const initChat = async () => {
넵 수정했습니다! 말씀해주셨는데 제가 잊었던 것 같습니다.

https://github.com/f-lab-edu/mezero-chat/pull/9

2024-10-12 03:48 UTC, nayoungace commented on app/chat/ChatDetailPage.tsx
> +  }, []);
앗 넵!! parameter 추가하면서 함께 수정했습니다!!

https://github.com/f-lab-edu/mezero-chat/pull/9/commits/442ee3927095a5b5abf56aeac8dad5ad909c78c4

2024-10-12 06:54 UTC, nayoungace commented on business/ChatService.ts
> +    return answerChat.title;
넵 무슨 말씀이신지 이해했습니다! createChatTitle 함수명을 updateChatTitle로 변경하였습니다.

https://github.com/f-lab-edu/mezero-chat/pull/9/commits/1f812a6af00115dd8ead686a6ccbfda86370a887

2024-10-12 07:04 UTC, nayoungace commented on business/ChatService.ts
> +    return answerChat.title;
race condition 이슈를 해결하는 방법... 이라고 하면 updateChatTitle을 동기적으로 작동하게끔 만들어주는 것이라 생각되는데요.
가장 쉬운 방법은 flag 변수 (지금 프로젝트에서는 사용자의 입력을 감지하는 isTyping) 를 설정하여 사용자가 chatLog를 생성하지 못하도록 하는 것이라 생각합니다.
더 좋은 방법이 ...! 있을까요 ?!

2024-10-12 07:19 UTC, nayoungace commented on business/ChatService.ts
> +  }
음 .. 이 함수도 createAnswerChatLog 호출하기 전에 isTyping의 boolean 값으로 조절했는데요.
말씀하신 race condition 포인트가 혹시 이 부분이 아니시라면...! 다시 생각해보겠습니다 ..!! :innocent:

2024-10-12 07:19 UTC, nayoungace commented
수정해서 반영했사옵니다!!

2024-10-12 09:07 UTC, f-lab-crack commented on business/ChatService.ts
> +    return answerChat.title;
요건 멘토링 시간에 좀더 이야기해봅시다.

우선 'race condition'이 무엇인지 물어볼테니 준비해오시길

2024-10-12 09:08 UTC, f-lab-crack commented on business/ChatService.ts
> +  }
네 요것도 조금 불완전한 방법인데 월요일에 이야기해봅시다

2024-10-12 09:09 UTC, f-lab-crack approved these changes
일단 요거는 merge하시고, race condition 관련해서는 이후에 다시 한번 PR을 해봅시당

2024-10-13 04:33 UTC, nayoungace commented
넵 알겠습니다..!!

2024-10-13 04:33 UTC, merged